### PR TITLE
More polymorphic input data | Blob support

### PR DESCRIPTION
**Pull request by Fresheyeball**

### CODE REVIEW

**Comment by imalsogreg** [comment]
Thanks for all the work! There are just a few things I'd like to see done before merging, since this adds some complexity: 
 - make sure that this works with the intended results (non-blocking streaming send of large payloads) in a full application
 - think about whether it would make more sense to change the xhr type in `reflex-dom`
 - think about whether this use case is better supported through a new `MimeType` or even a new API combinator (`StreamedBody a`), which would give the client an `OutputStream`-like thing in the client function `Event t (Maybe (PieceOf a)) -> subApiFunction`

**Comment by Fresheyeball** [comment]
> - make sure that this works with the intended results (non-blocking streaming send of large payloads) in a full application

Will do _prior_ to this PR being merged

> - think about whether it would make more sense to change the xhr type in reflex-dom

I don't think that is needed because `reflex-dom` already supports the types we need.

> - think about whether this use case is better supported through a new MimeType or even a new API combinator (StreamedBody a), which would give the client an OutputStream-like thing in the client function Event t (Maybe (PieceOf a)) -> subApiFunction

This would be a good thing, and the new typeclass `GHCJS'MimeRender` should support that. But this is still needed to achieve that support.

**Comment by imalsogreg** [comment]
@Fresheyeball 👍 sounds like a plan

**Comment by Fresheyeball** [comment]
@imalsogreg I can confirm this works in practice and streams things.

**Comment by imalsogreg** [comment]
@Fresheyeball Cool! What happens to the UI during streaming? Does is stay responsive to reflex events?

**Comment by Fresheyeball** [comment]
@imalsogreg let me check.

**Pull request merged**
