### PR TITLE
use the `BaseUrl` parameter to request an API

### PR DESCRIPTION
**Pull request by lethom**
(it's @Ikyushii)

Sorry for the delay, I’m workind on way too many projects right now… But as all of them are built upon servant and many of them will rely on servant-reflex, I’m still on board.

Hope this PR will suit you, anyway.

* Related issue: #3

### CODE REVIEW

**Comment by imalsogreg** [comment]
Thanks @lethom ! I'm going to leave the issue open because I think I want to give some more thought to what @3noch mentioned about wrapping some of the BaseUrl parts in a Maybe. This PR is a good start toward that.

**Comment by lethom** [comment]
Thanks!

**Comment by 3noch** [comment]
Good work @lethom! Yeah I still think we'll want the option of leaving out host and port.

**Comment by lethom** [comment]
Rather than modifying the `BaseUrl` argument, I would personally recommend to use `Either BaseUrl String`.

**Pull request merged**
