### PR TITLE
Bumping to latest reflex platform (reflex-dom 0.5 and reflex 0.6)

### PR DESCRIPTION
**Pull request by benkolera**
Bumped to latest reflex platform.

We have to eat pointing the test server at this fork (https://github.com/antislava/servant-snap) until I fix https://github.com/haskell-servant/servant-snap/issues/20 or (even better) https://github.com/haskell-servant/servant/issues/1166.

If you don't want to merge this until then and we don't need the non fork, that's OK. I can point to my fork while everything is a bit of a mess. Just thought I'd put it here in case you thought getting to the latest reflex was more urgent. :)

FYI: I likely wont get to fixing up servant-snap till after lambda jam Australia, so it's at least a month away if no one gets to servant-snap first.

Have run the webdriver tests. and the appear to pass with the previous overrides and patches removed and on the new platform. 

```bkolera at bkolera-qfpl in ~/src/github/imalsogreg/servant-reflex (reflex-dom-0.5●) 
$ nix build -f travis.nix testresults
trace: WARNING: ignoring dependency on doctest
[3 built, 0.0 MiB DL]

bkolera at bkolera-qfpl in ~/src/github/imalsogreg/servant-reflex (reflex-dom-0.5●) 
$ cat result 

Servant.Reflex
  servant-reflex tests
    test page using chrome
      opens the page
      has a div
      has demo-group div
      doesn't have demo-group-nonexistent div
      can get an int or unit from the API
      handle query params
      handles queryflag
      tags dyn promptly

Finished in 3.6154 seconds
8 examples, 0 failures
```

### CODE REVIEW

**Comment by imalsogreg** [comment]
@benkolera any idea why Travis is timing out now? Maybe `servant-reflex` and upstream `reflex-platform` are in disagreement about `nixpkgs` version, and we're no longer hitting obsidian's hydra cache?

**Comment by imalsogreg** [comment]
By not running tests for `SHA` under ghcjs (https://github.com/imalsogreg/servant-reflex/commit/d23b07efadb30bdf50ddcfcf86220e07752b02ab), we get farther, but CI still times out.

**Comment by benkolera** [comment]
(Sorry if this doesn't make sense. I've had this open for a bit and rewritten it a few times. :slightly_smiling_face: )

The reflex platform commit that I bumped it to is 8 days old (and from develop) and has been built by hydra. 

The reflex platform build that we are pointing to: https://hydra.reflex-frp.org/eval/194279

The last commit that servant-reflex was pointing to: https://hydra.reflex-frp.org/eval/80810#tabs-still-succeed

These don't look that different to me. What may have happened is that new dependencies came in servant 0.14 and new snap and that these new things aren't cached by reflex-platform builds. I do note that from servant 0.13 to 0.14 there are some extra http type packages and dependencies on hxt come in. If they are pulled in, then it's within reason that now with some extra source builds we bring in some new uncached test dependencies as well.

We are eating 38 more cache misses compared to before this PR (69 cache misses -> 107). Reflex caching was already not caching everything that we needed and now it's a little worse, so this sounds about right to me. We just have a few new bad things that have problematically slow tests in ghcjs. The lists are below of what we are and used to be source building if you are interested. 

Given that we're not overriding much (just servant-snap really: we get cache misses even if we don't skip the tests that we do) and that not much would depend on servant-snap, I don't think there is anything that we can do on our side to hit the reflex cache better. We could copy our closure to cachix which would speed up our builds and our users builds. Long term, I think that it is best to get a full-stack obelisk + servant app into reflex examples so that all of our stuff is cached with the reflex hydra.

Compiling GHCjs is slow, but running the tests are even slower. I can play the game where I squash the ghcjs tests one by one until the build works. It'll still be slow because we're building some ghcjs deps, but it should at least not time out if we squash all of the troublesome tests. At most they'll be 38 tests to skip, but should be much less.

To summarize:
- I don't think that we've broken anything and can't fix the reflex cache missing on our side . I think that reflex just isn't caching all that we want these days even worse than before given our deps have most likely grown their deps.
- I can play dontCheck whackamole till the bulid succeeds.
- We can optionally use cachix as a way to cache our builds to speed up CI (and users could use it too) but you'd have to sign up for a cachix and make a signing key.
- Long term plan would be to get a full stack servant + obelisk example into the reflex hydra so that it's cached in the reflex cache.



These are all of the things that are cache missing now (107, which is 38 more than before): 

```
  /nix/store/sxl75g4jkjcw8pp1v22sdy7i7kkf7gbx-logict-0.6.0.2.drv
  /nix/store/0fmf83215m6g1lc4kak85ablbn832v22-smallcheck-1.1.5.drv
  /nix/store/fcf2nj04whcgd0y917nggx64vhp9ck55-xml-1.3.14.drv
  /nix/store/k1hldh5jnn0babxckqaqjs68gz9hihqa-hostname-1.0.drv
  /nix/store/n25f3navxfmbfrd4k8n4qnmhrj8a99pg-regex-posix-0.95.2.drv
  /nix/store/6arkpdhj92k6vaqvjf9k7n87n83gj011-test-framework-0.8.2.0.drv
  /nix/store/pz4vs9naabbv0wzxhl2b11yh5p1zj0dc-extensible-exceptions-0.1.1.4.drv
  /nix/store/0pa9szazry6r42nn8ifrc7hgv94h7f00-test-framework-quickcheck2-0.3.0.4.drv
  /nix/store/rn0q2bpz5dmavxc2cl5ikwpd1rns5df6-hourglass-0.2.12.drv
  /nix/store/fls2jl6y1ril9ahgpxdhcnwlf938mpi2-asn1-types-0.3.2.drv
  /nix/store/h13xwnh3hlvxrg6cqnsi4mq6qms8ia72-asn1-encoding-0.9.5.drv
  /nix/store/5ns68qzx7x7q74v0nkz1d77bfgbchswb-crypto-pubkey-types-0.4.3.drv
  /nix/store/5sc09klzczsjpbdxd85gam92az7y3jh5-SHA-1.6.4.4.drv
  /nix/store/f883arqk251kb6cza97k5fxjm32m64kd-cereal-0.5.7.0.drv
  /nix/store/858d1ird7nhp44cqp1ynlld4grfl77kh-crypto-api-0.13.3.drv
  /nix/store/7236q34hnjjaiyyi7yj9p9sbm0534lqd-prettyclass-1.0.0.0.drv
  /nix/store/b11yfbsvvm9y3kgx5mk622hrdxw9q16l-cryptohash-cryptoapi-0.1.4.drv
  /nix/store/rb7dsw5q6sdd9ld3llpva21gcsz40bgq-cipher-aes128-0.7.0.3.drv
  /nix/store/h7pl46xrnasx88652pzkznqn16948a4q-DRBG-0.5.5.drv
  /nix/store/0s0c1ay8n3jr7sigiccgdsfr9h2z1cva-RSA-2.3.0.drv
  /nix/store/2i5jvapsrs4nmdvq2x35n4db996p5f28-test-framework-hunit-0.3.0.2.drv
  /nix/store/lqy4dfn5qb16cpaq3lxqzd512km4g4ny-securemem-0.1.10.drv
  /nix/store/6cr5ypilvcdcmljpn8z7ldi684ha8bgw-crypto-cipher-types-0.0.9.drv
  /nix/store/0x9gacrgjzwc9d4qj5b8ibklaawk0bh8-crypto-cipher-tests-0.0.11.drv
  /nix/store/1cgg2pc3a9k0d69hsbd5kjijmsya0k9d-http-common-0.8.2.0.drv
  /nix/store/38frkq3v8a1yr3lqs1vdly8n9606hpnm-zlib-bindings-0.1.1.5.drv
  /nix/store/395gmxjzf37d6qpdcdh9kq3b7pg38m0k-wcwidth-0.0.2.drv
  /nix/store/49pff177a4bnwfp5x3i2hqgsi92w9a78-cipher-aes-0.2.11.drv
  /nix/store/hf6nh1q1l8hqs5fm588wm0cgr9cdhjvh-pem-0.2.4.drv
  /nix/store/slchc8cd8nrls1sq2nkabrbm99nmy7lr-asn1-parse-0.9.4.drv
  /nix/store/gq2m1sikflvar93073iba8af5b8x4iyf-x509-1.7.3.drv
  /nix/store/4jc8h9vdd6wx0ly97v7kjz69kixq0s7q-x509-store-1.6.6.drv
  /nix/store/4xwzwffbs5ny2w0szv0fsqh0mxpczk1p-cookie-0.4.4.drv
  /nix/store/c18i61ygznsnffd8glkkgfvqcg86kvh7-map-syntax-0.3.drv
  /nix/store/yx3iqigf8d81bdlr03s5b8ig47p66kdn-xmlhtml-0.2.5.2.drv
  /nix/store/5ax3vh40h8yyaj96cq0dy1l9lk0v1asg-heist-1.1.drv
  /nix/store/a0kpihzvmd233i4czmlxihg2g19ws3d3-tasty-1.1.0.3.drv
  /nix/store/aw8mvjmhala5xp4qd4q43iyhaars2vri-tasty-hunit-0.10.0.1.drv
  /nix/store/gcl2jqns2xiabbzy8jny28psksfr3xap-pcre-light-0.4.0.4.drv
  /nix/store/5p034m7h9ghl6w9pmg8hmz3sqalkjqw1-tasty-quickcheck-0.10.drv
  /nix/store/5pvdc7di95gkcflyzxwvak0fxpn60lza-natural-transformation-0.4.drv
  /nix/store/62r03h4cb5vyh6ccj92cvma64rbva7nc-readable-0.3.1.drv
  /nix/store/64k9daskmb3g2fhcnis0jy72mai1lay5-string-conversions-0.4.0.1.drv
  /nix/store/6xljxkmgl04pkmlpqn1d45l3h84i619d-quickcheck-instances-0.3.18.drv
  /nix/store/9gpkvivb4fk6pwdh44kbn621fkrlvxq1-http-media-0.7.1.2.drv
  /nix/store/9wxmd6s3c2w2zvg2749pdin8x354jxw5-attoparsec-iso8601-1.0.0.0.drv
  /nix/store/x1lzx41gdb3ra505r8djdpc5bg7sa9np-generics-sop-0.3.2.0.drv
  /nix/store/ahg0vhaw8srrq6llxhjks3jsjxgi7gwf-uri-bytestring-0.3.2.0.drv
  /nix/store/mxz6li8jjrvfcbgz0936m9ck8bfzr6j5-cabal-doctest-1.0.6.drv
  /nix/store/b05qaz0hddq2l4ks1k8gdj69kl6maasv-http-api-data-0.3.8.1.drv
  /nix/store/bgipjr3zpm9hnpzay4bh7b02r0as3xdw-natural-transformation-0.4.drv
  /nix/store/rf3h56ck7c11dy71r89gwmymxiak6049-code-page-0.1.3.drv
  /nix/store/zccsddfpziqlf21402n1ivga1kih8281-ghc-paths-0.1.0.9.drv
  /nix/store/c6mxbvv8mp55nn4fz8bxyy7p1ghz983j-doctest-0.16.0.drv
  /nix/store/jgzkirmhfgw5cn5bvnxbgjb2ish7j9j4-string-conversions-0.4.0.1.drv
  /nix/store/lk5jy3bzafsd8q6ds2p5pr2rs7ic4knz-aeson-compat-0.3.8.drv
  /nix/store/rdn149khcyb52jdkjv40wvk1yvk8ddfa-singleton-bool-0.1.4.drv
  /nix/store/zyb99ri97ddnpb2yipi8grxvdiq0hcb3-mmorph-1.1.2.drv
  /nix/store/68fd2n0bjfa7dmffi3ixc0xv18653z3l-servant-0.14.1.drv
  /nix/store/6glz1grxp504ibx3xg32r6a8ks6xinkw-http-client-0.5.13.1.drv
  /nix/store/y42bdm8kiknwvf65di1y1bglzxdzg2yy-x509-validation-1.6.10.drv
  /nix/store/6h7wyww0zx6pcsfpsik84zqhimdjsnrf-tls-1.4.1.drv
  /nix/store/73g17zrkk20ia1rgj51kfb4s35xza28v-io-streams-1.5.0.1.drv
  /nix/store/jwxm2ah4jzfvszr6kk94nv8v4wqw0qr3-HsOpenSSL-0.11.4.14.drv
  /nix/store/bqnbj1d8h59kbha2j6d3asscg3s2bxjq-openssl-streams-1.2.1.3.drv
  /nix/store/dg2sbb6fy7cfp1zwcx5lxdais3zy3lib-io-streams-haproxy-1.0.0.2.drv
  /nix/store/i9acpnfwddvslf2i87j0xylfwn9x003z-snap-core-1.0.3.2.drv
  /nix/store/nrj9w5i17yb7szcj40g9y10zswv6y4rh-threads-0.5.1.6.drv
  /nix/store/zs9gvn1m9lsck5znd7n4kphbamh4n5ps-http-streams-0.8.6.1.drv
  /nix/store/70wwf34x4b4yz5fl048lalf5mla46y0k-snap-server-1.1.0.0.drv
  /nix/store/j74zgfcv8xfyffpfhmlcgb5v4aqyn421-test-framework-smallcheck-0.2.drv
  /nix/store/mx9gxcr9kdyvflq1dscka06rns1bi7sl-crypto-api-0.13.3.drv
  /nix/store/jp21qd73qab5nf6f7zvp5kyd1cb0jv9y-skein-1.0.9.4.drv
  /nix/store/n3vn6cdqkyzmc58xrwmif5igmzy80ysq-crypto-random-0.0.9.drv
  /nix/store/mjaq8blz9084la2z1qrqz2bw9g6cw2qi-cprng-aes-0.6.1.drv
  /nix/store/l6qgv399gy4ga3a98avh1mg0vpm0d5np-clientsession-0.9.1.2.drv
  /nix/store/fpjc08skyqbyg06k10m50y77d2q9pn5f-cryptohash-0.11.9.drv
  /nix/store/ql6az8rkc96kzjrqgwrvgcdlynbj1sdc-pwstore-fast-2.4.4.drv
  /nix/store/smm5hrglr6aa1w7wqn9vip5c87qnhm4l-configurator-0.3.0.0.drv
  /nix/store/dx630nw3si3kmm6px1bz010jcbrsby50-snap-1.1.1.0.drv
  /nix/store/xmib5c41mj790xblc0i92zvgdwczl106-either-5.0.1.drv
  /nix/store/b0l7pip4hxp02q24l8h8pwwqpg7wsqcy-servant-snap-0.8.2.drv
  /nix/store/i6zjplrppzjhp1igxp1c2rna80pzqsdp-x509-system-1.6.6.drv
  /nix/store/pjm6qs8hg7m5qz1rhjpz1w3mv448nwy9-byteable-0.1.1.drv
  /nix/store/rgas162g4n9qif9x8mby7pagkyq25lcp-socks-0.5.6.drv
  /nix/store/m4rjd3nxr50qjf39k66klpahhc8jzxqz-connection-0.2.8.drv
  /nix/store/h0wjn74r58lhkbzc8d06v15xashv4rca-http-client-tls-0.3.5.3.drv
  /nix/store/s3m9cd8bldw9ga665d1bvgppha66pkqr-simple-reflect-0.3.3.drv
  /nix/store/lvpynw2vcdd4vbdhhz8ypy5dl7sxl31p-lens-aeson-1.0.2.drv
  /nix/store/xb5fv9ccjg1f96ll9qwc7rcg90wya7ky-authenticate-oauth-1.6.drv
  /nix/store/9xy31r43kym3irrvfv660ckca362mqb2-wreq-0.5.2.1.drv
  /nix/store/7302xn6347qwrpd8qamv50c9lskshmq2-singleton-bool-0.1.4.drv
  /nix/store/c80sn10h2h0kbyjl2d1zsr6y8bm38wrr-attoparsec-iso8601-1.0.0.0.drv
  /nix/store/m10q7zfrwbcpihdcphz49k40gc1jkx4x-generics-sop-0.3.2.0.drv
  /nix/store/wqkfb9qpa7yjky46qsnslpip35w81rgg-uri-bytestring-0.3.2.0.drv
  /nix/store/klshmvsx0qikaghik195s4brhvak0r0z-http-api-data-0.3.8.1.drv
  /nix/store/km5dnv9cl61jzddrn9g1mgridy6bwcmf-http-media-0.7.1.2.drv
  /nix/store/n1w6j9mdhxj3k0q1bngh3p46acalzrz1-aeson-compat-0.3.8.drv
  /nix/store/vllxb7k94islajw9y0c8vhqsgi049hf8-mmorph-1.1.2.drv
  /nix/store/jy0sw2iqncjip1yf4581xlwnny6g2777-servant-0.14.1.drv
  /nix/store/k6zafyabr7fp16hnfh21yy34mmh041wf-servant-auth-0.3.2.0.drv
  /nix/store/yng6gifcfv59hxpqgp2869l9diy4vyww-parser-combinators-1.0.0.drv
  /nix/store/r55xncfpm7fqh39kw2jjbj5qgz3h6k2j-megaparsec-6.5.0.drv
  /nix/store/ngp214vvnw7kaaw0h02yhq76ac0xphaj-servant-reflex-0.3.4.drv
  /nix/store/6sgr8snv0hhzxsnq1yz46gkkr23qp3yz-testserver-0.1.0.0.drv
  /nix/store/ydjcl6p80vnswiy43sjm38jcy8gxkdnh-testdriver-0.2.drv
  /nix/store/qg523zf6765yvwqis7d3lgr4bxyhpa8x-runWebdriveTest.sh.drv
```

Here is the old list:
```
  /nix/store/08hgr8q2iv9lin7wcc8rjakzlik93whv-entropy-0.4.1.1.drv
  /nix/store/095mf6d2x34aha5wz7ghcrqlili47l4y-psqueues-0.2.7.0.drv
  /nix/store/n2dz3y09igrbmpbr5wn3755f2vacqj0c-heist-1.1.drv
  /nix/store/wbrbjh8wx605886xmmn2xgi214kzl93i-snap-server-1.1.0.0.drv
  /nix/store/5bfr10h3rwpdqx7q0bl1kn28i1l6prca-snap-1.1.1.0.drv
  /nix/store/pljyia6af73syijqk6as3v7kr327a945-string-conversions-0.4.0.1.drv
  /nix/store/vzxlblxh4ybq52rrl5dvj7lly6f40pm0-snap-cors-1.3.0.drv
  /nix/store/5k67l68a7vv1zw88wm0lpppm0ln7p7vm-natural-transformation-0.4.drv
  /nix/store/l4vk68qbkizd0bij2iy42ii0x7iaxvjb-http-media-0.7.1.2.drv
  /nix/store/ykfv9vsdsczn5mlwjhxhjk1y2x5kw4v2-servant-0.14.1.drv
  /nix/store/0gfyqb8626764jhlgxh1l07x0sbclbli-servant-snap-0.8.1.drv
  /nix/store/0s7mz2nxgj5v4kj0cgby4gy1wf963sl3-mime-types-0.1.0.8.drv
  /nix/store/8xrxsziy6sv4znly50ixi40yyvdscy57-basement-0.0.8.drv
  /nix/store/rjdzpgky4xx1f2657zbzicgpvicmzqyd-foundation-0.0.21.drv
  /nix/store/1dls7pds4mv2rm7d6jd6imsj3dlnjp66-memory-0.14.16.drv
  /nix/store/1zyn6di2hh6nzgmrbgbg1ljim38hn819-zlib-0.6.2.drv
  /nix/store/aml6q5xvdp94xi5xa7345cb72n775xc7-network-2.6.3.6.drv
  /nix/store/1infkmp380d89hjv2ly3aiqnwdx7r3c9-streaming-commons-0.2.1.0.drv
  /nix/store/afpdn244brm38das4m1782s9i81wmba6-generics-sop-0.3.2.0.drv
  /nix/store/h73b1rqax9l1nh6whcc3qw8qxyv9yxv9-uri-bytestring-0.3.2.0.drv
  /nix/store/x5pxcwkic8v5l9fvm9i9c977xcc19s7z-attoparsec-iso8601-1.0.0.0.drv
  /nix/store/2bh2pws1gz1k29jw6y0y4ddhbky19wgd-http-api-data-0.3.8.1.drv
  /nix/store/2z7dcw3xmzrracjzsh18r3d1acfr052f-cryptonite-0.25.drv
  /nix/store/q9mlzsf8ky5ipq1rsyjdqcmwkqw05v67-parser-combinators-1.0.0.drv
  /nix/store/b3mgi3r3iihwlmgahkgpv5m0m3rswngg-megaparsec-6.5.0.drv
  /nix/store/fvfgd6778dr2dqkyg5v0yxac13vdyji8-http-media-0.7.1.2.drv
  /nix/store/3rwypjrdfdis3y69xvxynaakf2v4w033-SHA-1.6.4.4.drv
  /nix/store/gs19d6qrj0pviap4yclgnyfm5m1qz98v-hourglass-0.2.12.drv
  /nix/store/r8zs5pqns3dcyy6i9z3mpi96zpplazwd-asn1-types-0.3.2.drv
  /nix/store/xjpbanp54p19r2n32lrdc1pw5kaf6lik-asn1-encoding-0.9.5.drv
  /nix/store/jjz2nm96xq39djg484lqgy7krh4v2aak-crypto-pubkey-types-0.4.3.drv
  /nix/store/qqv4530iya36ig7imw33d9lq3k4jdz2d-cereal-0.5.7.0.drv
  /nix/store/qvjfwmc9l7slxm9f9kvy8cjzb4jk83lk-crypto-api-0.13.3.drv
  /nix/store/j21km14kiscqg45xa7rmfylw1vvyk1h0-cipher-aes128-0.7.0.3.drv
  /nix/store/kd67miwqmz3k5iv5hazlq2z738z1f3pm-cryptohash-cryptoapi-0.1.4.drv
  /nix/store/qar6dxkizlvlm2603mwvqkdk4p5j40ci-prettyclass-1.0.0.0.drv
  /nix/store/wnqx1i1kh9q4f66nsjyxy9mhs5d90izq-DRBG-0.5.5.drv
  /nix/store/aqdhf5svqzqih7q0fqpbqmrid1znafh9-RSA-2.3.0.drv
  /nix/store/rg6vi17n4rfrihv14ai0czwbbjzjlmnk-cookie-0.4.4.drv
  /nix/store/ra5j3slxmz32fs5nw7mn1g4whncc85zb-http-client-0.5.13.1.drv
  /nix/store/48kqaw6c31m7pxrbhhgbxivc938ly751-authenticate-oauth-1.6.drv
  /nix/store/p6l1vn21nml6ixds8mnjfspxpcdbbl2p-simple-reflect-0.3.3.drv
  /nix/store/7xmfzl3z5fv5x4nxj1w219i9x8h1pka7-lens-aeson-1.0.2.drv
  /nix/store/hi7073wlr7y9k2sd9awfvqbasxv4v0n3-pem-0.2.4.drv
  /nix/store/zq7scxvh36b47wqiyi9c40sdlgv12ybd-asn1-parse-0.9.4.drv
  /nix/store/lgpyzqpjn363njh2337zl4gn5a1ggcz1-x509-1.7.3.drv
  /nix/store/j8fawysm6yqqxcga4hw5iza68c7x349g-x509-store-1.6.6.drv
  /nix/store/98378m4ybdf6yn1azhj8vasnk8yflbra-x509-validation-1.6.10.drv
  /nix/store/bqwfcwjxxi6iqz6m291qhcikzfscfl9s-x509-system-1.6.6.drv
  /nix/store/cqq089g4jhywgawyx65gx14vksw4ccfl-socks-0.5.6.drv
  /nix/store/hxdipwh5w22nzgwz8mxpwhi7v6jygqbr-tls-1.4.1.drv
  /nix/store/pf7w6s2p8ff2rzgxkrnqlv4ycarzjh90-byteable-0.1.1.drv
  /nix/store/76jz39z112ldhrhzvw7f6w4a1r6nvw0m-connection-0.2.8.drv
  /nix/store/8ac6j9lwfg3cybgpwmyx2lb2nkqbyh0g-http-client-tls-0.3.5.3.drv
  /nix/store/jmlin63w7nirf1zsh5w26qxl3l4kxvm3-wreq-0.5.2.1.drv
  /nix/store/li0kajy0j7sj0khlzmz8n4lgv7r1xpb8-string-conversions-0.4.0.1.drv
  /nix/store/5fnafb7pfxp34v9zsk7a70iv7q7qc5pf-natural-transformation-0.4.drv
  /nix/store/6dmi3asgdfm47vnlvv2i6wc0wn6rhn9z-mmorph-1.1.2.drv
  /nix/store/b2iwjl1wcgbyg9iv83ih9bgpblhldslv-singleton-bool-0.1.4.drv
  /nix/store/rhvqjz7qr193ry7n3p3mfgx0hzjdpg99-vault-0.3.1.2.drv
  /nix/store/p77dvz3ac1p986r8psz45lcnp8n4vhgr-servant-0.14.1.drv
  /nix/store/qmdxw6j7axg8s90awabbypnm6dqdfqxy-servant-auth-0.3.2.0.drv
  /nix/store/3amaamqiysw27fvp4i1p94frx8gx0smj-servant-reflex-0.3.4.drv
  /nix/store/4h9p3fxh2hrn2j9y1w5j2fbbgf2hir0x-zip-archive-0.3.3.drv
  /nix/store/cp98npxrb6mff9nziw8c5m0k9dy56f7j-testserver-0.1.0.0.drv
  /nix/store/s7nfqra4lmn0dfldpps1l0alznp10z9b-webdriver-0.8.5.drv
  /nix/store/pw3vmqjrijs4jf4j9xs47xg8fh7rvhpq-hspec-webdriver-1.2.0.drv
  /nix/store/yc5iggcpcnxhn9gyy7nm6vlzk0yc611p-testdriver-0.2.drv
  /nix/store/rq3lln3xlvqqh0z49d611wdmjym73m8w-runWebdriveTest.sh.drv
```

**Comment by imalsogreg** [comment]
Thanks for all that investigation! Since the tests pass locally, how about we merge  your PR, and I can make followup issues for cachix and an obelisk example?

dontCheck whackamole sounds less fun than the arcade version. I'd lean toward disabling tests for all our testsuite's dependencies uniformly in nix, or getting those tests run once on cachix.

**Comment by benkolera** [comment]
Cool, thanks for merging! :slightly_smiling_face: 

I'm always sad to leave CI in a worse state than when I arrived, but this ought to be fairly temporary so long as we don't have a bunch of new reflex and servant versions in the next few months.

**Pull request merged**
